import {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bath,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  Car,
  CheckCircle2,
  Clapperboard,
  CreditCard,
  Dumbbell,
  Flame,
  Fuel,
  Gauge,
  GraduationCap,
  Home,
  Landmark,
  Layers,
  Lightbulb,
  LineChart,
  Music,
  PiggyBank,
  Pill,
  Plane,
  ReceiptText,
  RotateCcw,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Tv,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react'

/** Registry so data files can reference icons by name (string) */
const REGISTRY = {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bath,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  Car,
  CheckCircle2,
  Clapperboard,
  CreditCard,
  Dumbbell,
  Flame,
  Fuel,
  Gauge,
  GraduationCap,
  Home,
  Landmark,
  Layers,
  Lightbulb,
  LineChart,
  Music,
  PiggyBank,
  Pill,
  Plane,
  ReceiptText,
  RotateCcw,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Tv,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
}

export function getIcon(name) {
  return REGISTRY[name] || Wallet
}

/** Merchant → icon rules, most specific first */
const MERCHANT_RULES = [
  [/salary|payroll|income|credit/i, 'Wallet'],
  [/college|fees|tuition|course|campus/i, 'GraduationCap'],
  [/gym|cult|fitness/i, 'Dumbbell'],
  [/pharmacy|apollo|medical|hospital|clinic/i, 'Pill'],
  [/netflix|prime|hotstar|bookmyshow|spotify|cinema|movie/i, 'Clapperboard'],
  [/swiggy|zomato|restaurant|cafe|pizza|bakery|food/i, 'UtensilsCrossed'],
  [/reliance|bigbasket|dmart|grocery|fresh|mart/i, 'ShoppingCart'],
  [/uber|ola|rapido|metro|bus|cab|taxi/i, 'Car'],
  [/indian oil|fuel|petrol|diesel|hp |bharat/i, 'Fuel'],
  [/amazon|flipkart|myntra|ajio|decathlon|meesho|nykaa/i, 'ShoppingBag'],
  [/electricity|power|bescom|energy/i, 'Zap'],
  [/wifi|broadband|fiber|jio|airtel|vi |vodafone|recharge|mobile|sim/i, 'Wifi'],
  [/lpg|gas|cylinder|water|rent|maintenance/i, 'Home'],
  [/insurance|policy|lic/i, 'ShieldCheck'],
  [/flight|train|irctc|travel|trip/i, 'Plane'],
  [/emi|loan|bank|credit card bill/i, 'Landmark'],
]

export function getMerchantIcon(description = '') {
  const match = MERCHANT_RULES.find(([regex]) => regex.test(description))
  return getIcon(match ? match[1] : 'ReceiptText')
}

export default REGISTRY
